### ISSUE TITLE
How to change the model type?

### ISSUE THREAD

**Issue by RomainGoncalves** [tomatophp/filament-media-manager#10]
Hi,

I would like to show a Customer model with the form for a folder so I can restrict access to some Customers only.

Customer has a 'user_id' field that I can use in the form, but I need to display the Customer's information in the form rather than the user info.

Is there a way to do that?

**Comment by 3x1io** [comment]
we have a morph relation for user_id, user_type so you can attach any type of users to the folder then control the access.
