### ISSUE TITLE
Error about dependency Iconpicker 

### ISSUE THREAD

**Issue by meniv-nl** [tomatophp/filament-media-manager#2]
After install, while creating folder I got an error "Class "TomatoPHP\FilamentIcons\Components\IconPicker" not found". 
Of course I can install the IconPicker package, but it would be easy if the package could be added to the dependencies.

**Comment by 3x1io** [comment]
okay i think we need to include the icon picker on composer.json thanks for report

**Comment by 3x1io** [comment]
fixed in v1.0.7
