### ISSUE TITLE
I can not install Filament media manager

### ISSUE THREAD

**Issue by janbulens** [tomatophp/filament-media-manager#22]
When I issue the command  _**php artisan filament-media-manager:install**_ I get the following error:
 SQLSTATE[HY000]: General error: 1005 Can't create table `mediadb`.`media_has_models` (errno: 150 "Foreign key constraint is incorrectly formed") (Connection: mysql, SQL: alter table `media_has_models` add constraint `media_has_models_media_id_foreign` foreign key (`media_id`) references `media` (`id`) on delete cascade)

**Comment by 3x1io** [comment]
i think you don't looking in to docs

```php
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="medialibrary-migrations"
```

then you need to run migrate

```bash
php artisan migrate
```
