### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by jvitasek** [tomatophp/filament-media-manager#4]
Hey, great job on this plugin!

Would you like some help with localizing the whole package? Not all strings are in the lang files, e.g. `Delete Media` and basically everything on the media detail, like:
```
<h1 class="font-bold">File Name</h1>
```

**Comment by 3x1io** [comment]
@jvitasek thanks for your report i will check it ASAP feel free to open PR if you like and I will be very happy to review it.
